config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :clients, except: [:destroy]
  resources :project_leads do
    resources :comments, only: [:create], module: :project_leads
    resources :phases do
      resources :comments,only: [:create], module: :phases
      get 'complete', on: :member
      post 'add_engineer', on: :member
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :users do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    root to: 'project_leads#index'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
end

app/models/project_lead.rb
# frozen_string_literal: true

class ProjectLead < ApplicationRecord
  has_many :phases, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  belongs_to :user
  belongs_to :project, optional: true
  belongs_to :client

  validates :name, :platform, presence: true
  validates :name, :platform, length: { minimum: 3 }

  enum sale_status: %i[open close]
end

app/controllers/project_leads/comments_controller.rb
# frozen_string_literal: true

module ProjectLeads
  class CommentsController < CommentsController
    before_action :set_commentable

    private

    def set_commentable
      @commentable = ProjectLead.find(params[:project_lead_id])
    end
  end
end

app/controllers/project_leads_controller.rb
# frozen_string_literal: true

class ProjectLeadsController < ApplicationController
  before_action :set_project_lead, only: %i[show edit update destroy]

  def index
    @project_leads = ProjectLead.open.includes(:client)
  end

  def show; end

  def new
    @project_lead = current_user.project_leads.new
    authorize @project_lead
  end

  def edit; end

  def create
    @project_lead = current_user.project_leads.new(project_lead_params)
    authorize @project_lead
    if @project_lead.save
      redirect_to @project_lead, notice: 'Lead successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @project_lead.update(project_lead_params)
      redirect_to @project_lead, notice: 'Lead updated.'
    else
      render 'edit'
    end
  end

  def destroy
    if @project_lead.destroy
      redirect_to project_leads_url, notice: 'Lead destroyed.'
    else
      render 'show'
    end
  end

  private

  def set_project_lead
    @project_lead = ProjectLead.find(params[:id])
    authorize @project_lead
  end

  def project_lead_params
    params.require(:project_lead).permit(:user_id, :client_id, :name, :platform, :sale_status, :created_at, :updated_at)
  end
end

app/views/project_leads/_form.html.erb
<%= form_with(model: project_lead) do |form| %>
  <% if project_lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_lead.errors.count, "error") %> prohibited this project_lead from being saved:</h2>

      <ul>
        <% project_lead.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class ='row py-4'>
    <div class="col-md-8 offset-md-3">
      <div class="form-group">
        <p><b><%= form.label :name %></b><p>

        <%= form.text_field :name, required: true %>
      </div>

      <div class="form-group">
        <p><b><%= form.label :platform %></b></p>

        <%= form.text_field :platform, required: true %>
      </div>

      <div class='form-group '>
        <%= form.label 'Sale Status'%>

        <%= form.select(:sale_status, ProjectLead.sale_statuses.keys.map {|sale| [sale.titleize,sale]}) %>
      </div>

      <div class="form-group">
        <p><b><%= form.label :client %></b></p>

        <%= form.collection_select(:client_id, Client.all, :id, :name, { :multiple => true }, { :prompt => 'Select Old Client', :selected => @project_lead.client_id })%>

        or <%= link_to "Create New Client",  new_client_path %>
      </div>

      <div class='row'>
        <div class='col-md-8 offset-md-3'>
          <button action = 'submit'  class='btn btn-dark px-3 py-2'> Create Lead </button>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/project_leads/edit.html.erb
<h5 class=" py-3 mb-2 bg-secondary text-white text-center">Update Lead</h5>

<%= render 'form', project_lead: @project_lead %>

<%= link_to 'Back', project_leads_path %>

app/views/project_leads/index.html.erb
<h3 class="bg-secondary text-white text-center py-2">Current Leads</h3>

<table class="table table-striped my-5">
  <thead class="thead-dark">
    <tr>
      <th>Lead Name</th>
      <th>Platform</th>
      <th>Client</th>
      <th>Creation Date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_leads.each do |project_lead| %>
      <tr>
        <td><%= project_lead.name %></td>
        <td><%= project_lead.platform %></td>
        <td><%= link_to project_lead.client.name, client_path(project_lead.client_id) %></td>
        <td><%= project_lead.created_at.to_date %></td>
        <td><%= link_to 'Show', project_lead %></td>

        <% if policy(project_lead).owner? %>
          <td><%= link_to 'Edit', edit_project_lead_path(project_lead) %></td>
          <td><%= link_to 'Delete', project_lead, method: :delete, data: { confirm: 'Are you sure ?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='row'>
  <div class='col-md-8 offset-md-5'>
    <%if current_user.business_developer? %>
      <%= link_to 'Create New Lead', new_project_lead_path, class: 'btn btn-secondary text-white'%>
    <% end %>
  </div>
<div>

app/views/project_leads/new.html.erb
<h5 class="py-3 mb-2 bg-secondary text-white text-center">New Project Lead</h5>

<%= render 'form', project_lead: @project_lead %>

<p class = 'mx-5 my-2'><%= link_to 'Back', project_leads_path %></p>

app/views/project_leads/project.html.erb
<h3 class="bg-secondary text-white text-center py-2">Current Projects</h3>

<table class="table table-striped my-5">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Platform</th>
      <th>Assignee</th>
      <th>Client</th>
      <th>Client Address</th>
      <th>Client Email</th>
      <th>Client Contact</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_leads.each do |project_lead| %>
      <tr>
        <td><%= project_lead.name %></td>
        <td><%= project_lead.platform %></td>
        <td><%= project_lead.user.name %></td>
        <td><%= project_lead.client.name %></td>
        <td><%= project_lead.client.address %></td>
        <td><%= project_lead.client.email %></td>
        <td><%= project_lead.client.contact%></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/project_leads/show.html.erb
<h3 class="bg-secondary text-white text-center py-2">Project Lead Details</h3>

<table class="table table-striped my-5">
  <tr>
    <th>Assignee</th>
    <td><%= @project_lead.user.name %></td>
  </tr>

  <tr>
    <th>Client</th>
    <td><%= @project_lead.client.name %></td>
  </tr>

  <tr>
    <th>Lead Name</th>
    <td><%= @project_lead.name %></td>
  </tr>

  <tr>
    <th>Platform</th>
    <td><%= @project_lead.platform %></td>
  </tr>

  <tr>
    <th>Sale Status</th>
    <td><%= @project_lead.sale_status %></td>
  </tr>

  <tr>
    <th>Creation </th>
    <td><%= @project_lead.created_at.to_date %></td>
  </tr>
</table>

<div class = 'my-2 mx-3'>
  <%= link_to 'Show Phases', project_lead_phases_path(@project_lead), class: 'btn btn-secondary text-white' %>

  <h3 class="py-2 my-2">Comments</h3>

  <%= render partial: 'comments/comments', collection: @project_lead.comments, as: :comment %>

  <%= render partial: 'comments/lead_form', locals: { commentable: project_lead_path(@project_lead) }%>
</div>