config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, only: [:index]
  resources :clients, except: [:destroy]
  resources :project_leads do
    resources :comments, only: [:create], module: :project_leads
    resources :phases do
      resources :comments,only: [:create], module: :phases
      get 'complete', on: :member
      post 'add_engineer', on: :member
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_scope :users do
    get '/sign_in' => 'devise/sessions#new'
    get '/sign_up' => 'devise/registrations#new', as: 'new_user_registration'
  end

  devise_for :users, skip: [:registrations]
  as :user do
    root to: 'project_leads#index'
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lead Management</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
      <a class="navbar-brand text-white">Lead Management</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarText">
        <% if user_signed_in?  %>
          <ul class="navbar-nav mr-auto">
            <li class="navbar-text px-2">
              <%= link_to 'Leads', project_leads_path %>
            </li>

            <li class="navbar-text px-2">
              <%= link_to 'Clients', clients_path %>
            </li>

            <li class="navbar-text px-2">
              <%= link_to 'Projects', projects_path %>
          </ul>

          <span class="navbar-text px-2 text-white">
            <%= current_user.name %>
          </span>

          <span class="navbar-text px-2 text-white">
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          </span>

        <%else%>

          <span class="navbar-text">
            <%= link_to "Sign in", new_user_session_path %>
          </span>
        <%end%>
      </div>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>